osx_instance:
  image: mojave-xcode-10.2

build_task:
  env:
    CSC_LINK: https://drive.google.com/uc?export=download&id=1kjg-b8a8avYpCAyvEtNiADLi92R3Lqt4
    CSC_KEY_PASSWORD: ENCRYPTED[2135896f7dac7c52c6cd4dd747130fb34cf717d0dff7da267cc9582c883fc6155fdfb98f0799c304dd7f44ab89bbb5c1]
  yarn_script: brew install yarn
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  build_script: yarn dist
