osx_instance:
  image: mojave-xcode-10.2

build_task:
  env:
    CSC_LINK: ENCRYPTED[f590d340be99029a4137ca003a74a614bfbe7ab9a683f222a1912d7692ccb1eceb7dbeeea2d963bca52737456772ee48]
    CSC_KEY_PASSWORD: ENCRYPTED[951c38315572de077af72022aabf5ecac546ccce2ff4be193765ff3d8fd47a4ff837b420d789958c9c30565c28e46944]
  yarn_script: brew install yarn
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  build_script: yarn dist
