osx_instance:
  image: mojave-xcode-10.2

env_task:
  env:
    CSC_LINK=https://drive.google.com/uc?export=download&id=1kjg-b8a8avYpCAyvEtNiADLi92R3Lqt4
    CSC_KEY_PASSWORD=ENCRYPTED[8d06c5f46b4b0294102eb2e38a69e9d30b5fdc8968f91159f2047879cab137ab34dd46e5aafc2ca7f9b10cf350396486]

build_task:
  yarn_script: brew install yarn
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  build_script: yarn dist
