osx_instance:
  image: mojave-xcode-10.2

env_task:
  env:
    DEBUG: electron-builder
    CSC_LINK: https://drive.google.com/uc?export=download&id=1kjg-b8a8avYpCAyvEtNiADLi92R3Lqt4
    CSC_KEY_PASSWORD: ENCRYPTED[951c38315572de077af72022aabf5ecac546ccce2ff4be193765ff3d8fd47a4ff837b420d789958c9c30565c28e46944]

build_task:
  yarn_script: brew install yarn
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  build_script: yarn dist
