os: osx

language: node_js
node_js:
  - "10.15.3"

before_install:
- openssl aes-256-cbc -K $encrypted_4631d445613d_key -iv $encrypted_4631d445613d_iv -in Certificates.p12.enc -out Certificates.p12 -d

env:
  global:
    - secure: cdxmn+QiHUYjFksqnDRvwrib3tdp2a2R7pZpzJBgx53nB0cm+WYcpiQcMNYTzfFqXH+3PYJXv+lI55uNQzacnT6QPQ7iWVLTBzjg8CaqvkvFKAlZK22ypHPizFNNVYyLK3wGItE1DS+qTdXH+KXRBpthTYGqIH02dwhQs7HRCdVFeqRcdAE8UcVT0+BjW6G1kWe2EaRfzzmAssguWSkmd6cTmNJph5VN3cplEAYF+lMPg37ukab38hMbgiEJ8zUDr8fl3R4jgw/qSsc1I4EQm+I55MOJP6CY0OfIHatQRJZnO6xFukYef6J9CDQwY0JRcB9IiFhzRRmk/6xWJuSxlcD7lKoeJgQuzdcKpn2ZRGPS3QT1d2zWE484TyqrSrXz7uiHwDfIvRZ420mAQqgj+wwCRbMncqOk1RhU65BFdw4Vg5xBuatOH+jTndhdRzIZp+7ShuTzBb/H7d2iLOI1CdomzDRHtSCBXIpyy094evUe9sBnx5y52n6XP9jld877Xe4fpKOcrPFuuJeORT1G6UvfXSrSI4exemGtrL0+Diu1YytIIXBFqMQLk9+3jedyVdvBoh/EgO3ClXHCLlyZm3zhSMj0hVs+eJ+J34qlU2Uwfjbf2gla/clemwgkwl6RHMzfTgCCs1r5KkWp/5FylxxWO3yQ+d1T9itZGg5c9TI=
    - CSC_LINK="./Certificates.p12"
    - secure: "mpXkZo/lKTXcFcWdtWnylywVb5U1XBQWbELvIRf/GcmcHRo+oun0GBe4Hl7Un2zJaOO9FzSTTNGWklF9ACESgjH4z3e8nX+bmyMTOhAna4lPz/1GqEGVfeVagYs6XEoGBuah0gDWzYXpU2mfOPZWNLuelsyLllxkZRXEudijRuCxM6qoCw7jR1M16hC3+G6c0EkmXtaGlkezDhQ2B9c+kTHrnERN2qsXtvrn+9n6j7ALa7r6RzRlaHSk9dcFnx5ykgKPiv0MmKQQSXZopEx2rzWu4LKIxsz+Lnu4jBlOtVbYAYx/JTrBln7NkTMWpAcBB5JN8/r9ucsWdr1Q78OQt84gTyLA8Na6K6LI5cw0wXAd//1WwpWZSkns3747yHYLD+HZXl/aBVshashxLkawb0ZD3h2iamjNmX905WZkzbWAkRXpggiRcNoBiwBNxjpNeRdbKCnS9edvYgQBEr8VlLs78wzzPrTPrbkxTWuU/iVcve0Xd5EdE6bHYMF7sIrjtAhyvUz39peH1LLGxyynU+jgcx3j41imB11dvTr3qCahoCDS5gRjsbYbb3YmilDr316GIiCI8GHLN/6JZdwKprsDJGjPAWGMsXusv+OCQEO46fYflGvDbxtuMdcVoq7jOAS4qBve3EXFWW+8aMee6qTSb88jclYKg8DZWUh+HZo="

install: yarn

script: yarn release
