language: node_js
node_js: "12.0.0"

# These $encrypted variables get set automatically in the CI environment when encrypting files via the Travis CLI
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then openssl aes-256-cbc -K $encrypted_4631d445613d_key -iv $encrypted_4631d445613d_iv -in Certificates.p12.enc -out Certificates.p12 -d; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then openssl aes-256-cbc -K $encrypted_02979d1f7724_key -iv $encrypted_02979d1f7724_iv -in adminal_code_signing.pfx.enc -out adminal_code_signing.pfx -d; fi

install: yarn --link-duplicates

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - CSC_LINK="./Certificates.p12"
        # CSC_KEY_PASSWORD
        - secure: "cdxmn+QiHUYjFksqnDRvwrib3tdp2a2R7pZpzJBgx53nB0cm+WYcpiQcMNYTzfFqXH+3PYJXv+lI55uNQzacnT6QPQ7iWVLTBzjg8CaqvkvFKAlZK22ypHPizFNNVYyLK3wGItE1DS+qTdXH+KXRBpthTYGqIH02dwhQs7HRCdVFeqRcdAE8UcVT0+BjW6G1kWe2EaRfzzmAssguWSkmd6cTmNJph5VN3cplEAYF+lMPg37ukab38hMbgiEJ8zUDr8fl3R4jgw/qSsc1I4EQm+I55MOJP6CY0OfIHatQRJZnO6xFukYef6J9CDQwY0JRcB9IiFhzRRmk/6xWJuSxlcD7lKoeJgQuzdcKpn2ZRGPS3QT1d2zWE484TyqrSrXz7uiHwDfIvRZ420mAQqgj+wwCRbMncqOk1RhU65BFdw4Vg5xBuatOH+jTndhdRzIZp+7ShuTzBb/H7d2iLOI1CdomzDRHtSCBXIpyy094evUe9sBnx5y52n6XP9jld877Xe4fpKOcrPFuuJeORT1G6UvfXSrSI4exemGtrL0+Diu1YytIIXBFqMQLk9+3jedyVdvBoh/EgO3ClXHCLlyZm3zhSMj0hVs+eJ+J34qlU2Uwfjbf2gla/clemwgkwl6RHMzfTgCCs1r5KkWp/5FylxxWO3yQ+d1T9itZGg5c9TI="
    - os: linux
      services: docker
      env:
        - CSC_LINK="./adminal_code_signing.pfx"
        # CSC_KEY_PASSWORD
        - secure: "0gZRC4EFhdlWqcHJ28i7RBhyIY3/UBXTpwUnyxB3UGIW39r3Kpfh75Fm0ZrQM1tnRy99F19qDnwpTHCMqTx38aaMHmQkekhM5HRbtmq32WGW7g20zeT323YBQ6d4i9nAaXO4bJJinPynCM99QG/82okSsezR5JNruyPXkRDxK4Rhsc9tt/fqh/IisemDUcyHjKKkuhXJr5Vqi4rkFzBEQ4gnibBuV6X9wl7hLH8Yh/Qh4xG/hc77zPkhO8MlQlpQ+Tm7kwFc7a4X4Th4RbG9rwLb/slRGc6/Bk18C81hVlBvXhj1XlG2XoD6ZJ6svNG1dDX31/AKC2qgiBAtoBLAsZdW+wGFPUUg23cQVOPcOu8I5QJjKyTAMM6WHITxrsqA+RKk2ywArAv5z3lxkKVCES5V/0lqtyHxniIRir7UcaS6cJAidoYZggRnTVBJI2mPKMaq8rFPZP0VvpQmn1Sqw/XknWg2HC1nm8W1QV4buA21EtX08lf99H+Q2xgcHdD+VpecglsCXJj1dzlQ6jpOMw++gyINfKjcvVy6Ufj0tBjYuR9L0IAmjw8dqV2Hle53V4QcVfstvYN5idYJ2KDb6MRh2GK9bwPJUbkSlS3bbL9ofWGw1VnXeXcJywgeulaHwGuBlkxwQsPLZasDBaIBfLUVkB00DtDQu8uHEgkNc/w="

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - yarn compile-prod
  - |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      docker run --rm \
          -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
          -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
          -e CSC_LINK=$CSC_LINK \
          -v ${PWD}:/project \
          -v ~/.cache/electron:/root/.cache/electron \
          -v ~/.cache/electron-builder:/root/.cache/electron-builder \
          electronuserland/builder:wine \
          /bin/bash -c "CSC_LINK=${CSC_LINK} CSC_KEY_PASSWORD=${CSC_KEY_PASSWORD} yarn dist --linux --win"
    else
      CSC_LINK=${CSC_LINK} CSC_KEY_PASSWORD=${CSC_KEY_PASSWORD} yarn dist
    fi
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  only:
    - /^v*\d+\.\d+\.\d+(-\S*)?$/
    - feature/FUA-142-code-sign-windows-artifact
