language: node_js
node_js: "10.15.3"

before_install:
- openssl aes-256-cbc -K $encrypted_4631d445613d_key -iv $encrypted_4631d445613d_iv -in Certificates.p12.enc -out Certificates.p12 -d

env:
  global:
    # LIMS_HOST
    - secure: G/dcEWo1AYTGYFWyDdYWLIOOKzFUmJzp/AY/0D7dXwZ0u2SW5d7JBq1/LUnzKDoOIOk3gYqnB8iPU4sbexfz7xZTX/nldNBgKHCaI8/p3cZB+733a7W+8MVjdHaHSBA5AffVx1uEJ9UpTaspA5nGytj6/Rq0IMU9ZX/WZV8amhmVj0g2RIVqv56fxUin71wXLfX1KZ2HtQcTL5a/Pq0yDPKHlJEHq4wCWul2mos5k9Hgv1JgoYe893hvXy2cTcgDwgolaU7UmlFYCuzPwW4aGkMGxtJ+EcwZVK5eNlVM2s84WCJE8lMptkJSb/MFhTNvvOEhGV6/+qaAPKZw09IhIj9YeBhbwEmyrPt/xKIjVY0IS2TIrq5MsWMPw0viwKRc/tu12l2X2Rvr/+vDePw6Rx+w8z5JJohrJMcnWxLEKPkaOvI6xdtjnvX4w40DvmaJFPybK3kGgkJrEBj5XTZmC57TbP6T/vjarF8Y8LVhcsjXVHNvUY+lxsm8P0Q02PCX+hwivrCYRWiYGETue1gU39uUTi0cpUFyH0PnXk3ReFHkKnLqSHLYVSr/e5qjQQZsuYnJojB0V5uXjxLFe6N1c+BG0RvJGriYC4ZOF4xWXjSOIjmVZM3jz2dWxonuUzQTVrWVWFxOsg+YPd5TWvtE3WrPRI/6//CddrGxrsob4u4=
    - LIMS_PORT=80
    # GH_TOKEN
    - secure: uaS5JuChbc7hnoHf51pTtquywWBnQzPPJbQRLsuxPNzhv9dfbj3znMMZAj9m/0QjA4H9AK9ruyXe8eMebf5KNGjbWMHk3vMctskFR9Ob2JVTr7uRFnGb5hq7/HYZbCvczdd4x2IlgGMtVmZLpNB7j8q72X+/Ft+Z7EUz4RWD8ycwl5nOHrGRKNkg4hA3l7NdQYyowCMbA9CU5SPWf64SoYqkRLC5umVYvRxc7qsgmdcRFOlpPfqUXfnyih2cQrhLVWwkt4ZtewhkmHFcvsQRdMz74Vil/V7qPNJUNlZrxLQBot53usqIQ36fpIkuW3uvm0l6Zx1E7ItSb5d82gN4cL4JfyedovQi33aNZI9JMdXtjQUSLwqX+3YuO8aPLZyFGivgsY7FNTjeTpBliNgZmj4ZY8xugkNHvl6Q8ooCfvN7aSlWW0G0VaOOy1GNcpl+TT1f8uuHw20bNWjgsK3XYiGauVCOahM9RuTZNcJSRAvL+JIqWhZ/AIRIFTjOYv/2OmDYxkA0EJ3KrE5WG2hrCKuCWAb3Oa1PttmSVpvikbhRNDSrPJcKcTkV8JP8ufoEKF+NP+9VvgPr45s7xnbc0/utVrDBDLbmGvIVCC6RVCLyNVjSSMbCceHnfj+CcIlYM4Y4Z+2vJDc9Iw5AO4tTOXyg9ZumCZq1RSjqQF1uueQ=
    # CSC_KEY_PASSWORD
    - secure: cdxmn+QiHUYjFksqnDRvwrib3tdp2a2R7pZpzJBgx53nB0cm+WYcpiQcMNYTzfFqXH+3PYJXv+lI55uNQzacnT6QPQ7iWVLTBzjg8CaqvkvFKAlZK22ypHPizFNNVYyLK3wGItE1DS+qTdXH+KXRBpthTYGqIH02dwhQs7HRCdVFeqRcdAE8UcVT0+BjW6G1kWe2EaRfzzmAssguWSkmd6cTmNJph5VN3cplEAYF+lMPg37ukab38hMbgiEJ8zUDr8fl3R4jgw/qSsc1I4EQm+I55MOJP6CY0OfIHatQRJZnO6xFukYef6J9CDQwY0JRcB9IiFhzRRmk/6xWJuSxlcD7lKoeJgQuzdcKpn2ZRGPS3QT1d2zWE484TyqrSrXz7uiHwDfIvRZ420mAQqgj+wwCRbMncqOk1RhU65BFdw4Vg5xBuatOH+jTndhdRzIZp+7ShuTzBb/H7d2iLOI1CdomzDRHtSCBXIpyy094evUe9sBnx5y52n6XP9jld877Xe4fpKOcrPFuuJeORT1G6UvfXSrSI4exemGtrL0+Diu1YytIIXBFqMQLk9+3jedyVdvBoh/EgO3ClXHCLlyZm3zhSMj0hVs+eJ+J34qlU2Uwfjbf2gla/clemwgkwl6RHMzfTgCCs1r5KkWp/5FylxxWO3yQ+d1T9itZGg5c9TI=


install: yarn

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - CSC_LINK="./Certificates.p12"

    - os: linux
      services: docker

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - NODE_ENV=production yarn compile
  - |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      ./docker-run.sh
    else
      echo TRAVIS_OS_NAME $TRAVIS_OS_NAME
      CSC_LINK=${CSC_LINK} CSC_KEY_PASSWORD=${CSC_KEY_PASSWORD} yarn dist
    fi
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

#branches:
#  except:
#    - "/^v\\d+\\.\\d+\\.\\d+$/"
#    - master
