name: Test AICS File Upload App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initialize
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Check for Circular Dependencies
        run: npm run madge
      - name: Unit Test
        run: npm run test
      - name: Compile
        run: npm run compile
