name: Test AICS File Upload App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initialize
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Corepack enable
        run: corepack enable
      - name: Yarn Version
        run: yarn set version stable
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Check for Circular Dependencies
        run: yarn madge
      - name: Unit Test
        run: yarn test
      - name: Compile
        run: yarn compile
