name: Test AICS File Upload App
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#       - name: Initialize
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.9
      - name: Initialize
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Install Dependencies & Lint
        run: ./gradlew -i yarn lint
      - name: Detect Circular Dependencies
        run: ./gradlew -i detectCircularDeps
      - name: Unit Test
        run: ./gradlew -i test
      - name: Compile
        run: ./gradlew -i compile
