name: Test AICS File Upload App
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initialize
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install --network-timeout 100000
      - name: Lint
        run: yarn lint
      - name: Check for Circular Dependencies
        run: yarn madge
      - name: Unit Test
        run: yarn test
      - name: Compile
        run: yarn compile
